### ISSUE TITLE
开源？ 

### ISSUE THREAD

**Issue by wotermelon** [hepengwei/sphere-collision#2]
开源？

**Comment by hepengwei** [comment]
> 开源？

是的，该库已开源，可以免费使用

**Comment by wotermelon** [comment]
> > 开源？
> 
> 是的，该库已开源，可以免费使用

没有源码

**Comment by hepengwei** [comment]
> 

目前还没有开源源码的计划，如果想要学习源码核心逻辑，可以参考这篇文章：https://www.jianshu.com/p/f449f425eefe
