### ISSUE TITLE
作者不考虑开源吗？

### ISSUE THREAD

**Issue by shown-zhang** [hepengwei/sphere-collision#5]
确实是一个非常棒的库，可以大大减少开发工作量，但是我看到仓库里只有打包后的文件。
这个是付费的吗？ 为什么不提交源码呀？

可以的话， 求一下 QAQ～

**Comment by hepengwei** [comment]
> 确实是一个非常棒的库，可以大大减少开发工作量，但是我看到仓库里只有打包后的文件。 这个是付费的吗？ 为什么不提交源码呀？
> 
> 可以的话， 求一下 QAQ～

暂时没有开放源码的计划，非常感谢支持

**Comment by shown-zhang** [comment]
好吧😑
